### PR TITLE
cmake build system ready

### PR DESCRIPTION
**Pull request by hanfeng0114**
Author:    binguang.zhao <binguang.zhao@linux.alibaba.com>
Date:      Sat Jul 2 14:23:16 2022 +0000

add cmake build system

### CODE REVIEW

**Comment by hanfeng0114** [comment]
Add more info:

1. This update is for the following features:
> seperate handcar repo as a standalone one with cmake system support
> add IDE(e.g. vscode, clion) support
2. handcar standalone repo is the next work we should discuss
> should we seperate another repo to maintain handcar, or use some muti-repo tool like google repo?

**Comment by rchu-futurewei** [comment]
Reviewed, ok to merge.  Also, since handcar is highly integrated in FORCE functionality, it should remain in same repo as FORCE as one consistent unit.

**Review by MikeOpenHWGroup — CHANGES_REQUESTED** [review]
Hi @hanfeng0114.  OpenHW requires open-source contributions to our repositories to be licensed under Solderpad 2.1, Apache 2.0 or Eclipse 2.0.  (Solderpad is preferred.)  Are you legally able to update these licenses to one of these?

**Comment by DBees** [comment]
Hi @hanfeng0114 thank you for the pull request.

@MikeOpenHWGroup have spend some time reviewing the files and their licenses to see if we should merge these with respect to licenses, copyright, etc.

There are quite some files with an Apache 2.0 license and copyright statement by Alibaba. No problem that we can see there.

There are others (Check-style.sh, FinCatch.cmake, Libsize.pay, Mkdoc.py, and some others) with no license statement. For the files with no license statement, are you able to attach an Apache 2.0 license and Alibaba copyright? If not, can you find the author of those files and find out which license they are contributed here under? 

Then there are those such as 
FindPythonLibsNew.cmake, pybind11Tools.cmake, FindEigen3.cmake in which either a BSD like license is stated or referred to. There should be little problem in redistributing (under Apache 2.0) or modifying and redistributing under Apache 2.0,  So I'd recommend that the Alibaba contribution include an additional Apache 2.0 header with the statement "This file is redistributed according to the terms of the original license below". That statement should also include a statement of what has been added or modified in the file by Alibaba along with a copyright statement covering those additions or modifications.

If you can make your best effort to handle those cases, we can then also request the Eclipse IP team for a further review to check that we have covered all the angles. 

Thank you again, Duncan

**Comment by hanfeng0114** [comment]
Hi @DBees , @MikeOpenHWGroup 

The files in 3rd_party/tools I added are just some files from pybind11 project, which I didn't make any modifications. So what about just adding some license notification info in file "NOTICE" like what pytorch project did(https://github.com/pytorch/pytorch/blob/main/NOTICE), with info:

All files in 3rd_party is not part of the FORCE-RISCV source code. Their licenses can be found under each directory of 3rd_party or the file hearder of files in 3rd_party.
All files in 3rd_party/tools is part of pybind11(https://github.com/pybind/pybind11) project, which follows LICENSE policy in 3rd_party/tools/LICENSE.

**Comment by hanfeng0114** [comment]
@DBees relative changes have been checked in.

**Comment by MikeOpenHWGroup** [comment]
Hi @hanfeng0114, your last update to this PR was submitted from a different account that is not covered by your ECA:
image
You will need to either rebase these updates to ensure they are from your `hanfeng0114` account, or get your `binguang.zhao` account covered by the ECA.

**Comment by hanfeng0114** [comment]
I have update my eclipse acount email. please check again.
@DBees @MikeOpenHWGroup

**Comment by DBees** [comment]
@hanfeng0114 @MikeOpenHWGroup I'm going to merge this in and suggest we request the EF IP team to review this approach. We need a committer who is familiar with the issues to raise this - is that you @MikeOpenHWGroup?

**Pull request merged**
