### PR TITLE
RV32 support for instruction and register builders

### PR DESCRIPTION
**Pull request by ahmedgalalramzy**

### CODE REVIEW

**Comment by Leo-Wang-JL** [comment]
Thanks for the pull request, reviewing.

**Review by Leo-Wang-JL — CHANGES_REQUESTED** [review]
Thank you for the pull request!

I'd like to suggest some file name modifications to the newly added instruction files before recommending merging the pull request.

The current instruction file naming using the official RISC-V extension letter to form a relatively short file name, for example:
c_instructions.xml

Please follow this convention.  Taking a newly added instruction file as example:
"riscv_instructions_double.xml"

The riscv_ part is redundant.  To fit in better with the current instruction files, the name "d_instructions.xml" is preferred.

Also for "riscv_instructions_int64.xml", the name "rv64i_instructions.xml" is preferred.

For the files in the arch_data directory, the rv64 part of the file names can be omitted.

For the files in the arch_data_rv32, the rv32 part of the file names can also be omitted, since they are already in arch_data_rv32 directory, but it is fine to leave that part in as well/.

**Comment by Leo-Wang-JL** [comment]
Looks good!  Thank you!

**Comment by Leo-Wang-JL** [comment]
Please assign to Mike Thompson (MikeOpenHWGroup) for merging.

**Comment by ahmedgalalramzy** [comment]
Main regression and unit tests regression run at 100% success right now. I should have only included the instructions labelled "supported_". Now it should be fine.

**Review by Leo-Wang-JL — APPROVED** [review]
Changes look good and regression passed.

**Comment by Leo-Wang-JL** [comment]
The changes looks good.  Please assign to:
@MikeOpenHWGroup
MikeOpenHWGroup

To merge.

**Comment by ahmedgalalramzy** [comment]
I don't have write permissions so I can't add an assignee. Can you assign him please?

**Review by Leo-Wang-JL — APPROVED** [review]
Code reviewed, tested, approve request.

**Review by MikeOpenHWGroup — APPROVED** [review]
Approving as per @Leo-Wang-JL request.

**Pull request merged**
